### ISSUE TITLE
Getting `undefined method `highlight' for nil:NilClass` after upgrade

### ISSUE THREAD

**Issue by dkinzer** [projectblacklight/blacklight#2234]
After we upgraded from v7.3.0 to v7.4.0, we started to see some errors when rendering dummy/empty Solr documents (which we use in place when an id does not return a document from the server).

We believe we can attribute this error to the following change: https://github.com/projectblacklight/blacklight/compare/v7.3.0..v7.4.0#diff-7142b8c9bd0a0da70267f8ebdf09ae49L24-L28

We can duplicate the error in the console

```
doc = SolrDocument.new({})
index_presenter(doc).heading
```

The above throws the error we are reporting (`undefined method 'highlight' for nil:NilClass`)

However the old code returns an empty string as would be expected
```
document = SolrDocument.new({})
index_presenter(doc).label document_show_link_field(doc), {}
# returns ""
```

## Update:
I looked into this issue further this weekend and I realize now that the issue is more related to blacklight_configurations.  The above result is probably OK in terms  an error as if a document does not have either a title or an id it should error out.

The issue is happening because on our site we have both SolrDocument and PrimoCentralDocument.  PrimoCentralDocument implement the Document interface but they have their own set of field configurations including it's one set of unique_key map.  Part of what happens is that on the bookmark view documents can be any combination of SolrDocument or PrimoCentralDocument types.  And in order to render without errorring the blacklight_config must be able to switch to the proper set per document... i.e. when I render a PrimoCentralDocument bookmark I better be using the primo_central_controller.configuration.

Anyway, prior to this change we were not seeing this error because we were swapping the @blacklight_configuration reference between document renders in the view layer.  However, now that everything is moving to the presenter layer, we need to figure out a way to pass the correct configuration per document render at the presenter level.

This issue is actually related to and a consequence of this issue projectblacklight/blacklight/issues/1878 which I closed but now I feel like that was premature.

I think that at some level since blacklight has a Document Interface it doesn't make sense that bookmark controller assumes that all documents it renders will have the same configuration.  This is a bug in how the controller is implemented.

**Comment by dkinzer** [comment]
Note this issue is also happening in version `v7.5.0`, where we debugged it.

**Comment by dkinzer** [comment]
Following thread further determined that this line returns nil and is part of issue:
```
f = fields.lazy.map { |field| field_config(field) }.detect { |field_config| retrieve_values(field_config).any? }
```
