### ISSUE TITLE
In 4.6, overriden page_entries_info breaks for non RSorl::Response collection

### ISSUE THREAD

**Issue by glampr** [projectblacklight/blacklight#686]
I'm using `page_entries_info` for normal ActiveRecord collections in my Rails app.

After upgrading to 4.6, this method breaks with:

```
undefined method `humanize' for MyXYModel:ActiveModel::Name

Extracted source (around line #44):
     <div>
       <%= page_entries_info @collection %>
       <%= paginate @collection, :theme => 'twitter-bootstrap' %>
     </div>
```

whenever I'm trying to paginate a normal AR query, and not a Solr response.
